//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteDUT
{
    using System;
    using System.Collections.Generic;
    
    public partial class LienKet
    {
        public string MaLienKet { get; set; }
        public byte[] AnhDaiDien { get; set; }
        public string Duongdan { get; set; }
        public string TrangThai { get; set; }
    }
}
