//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteDUT
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuangCao
    {
        public string MaQuangCao { get; set; }
        public string TenQuangCao { get; set; }
        public string DuongDan { get; set; }
        public byte[] AnhDaiDien { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public string TrangThai { get; set; }
    }
}
